service: booking-api
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:AWS_PROFILE}
  region: eu-north-1
  iam:
    role: ${env:AWS_IAM_ROLE}


plugins:
  - serverless-webpack


package:
  individually: true


functions:
  getRooms:
    handler: functions/getRooms/index.handler
    events: 
      - httpApi:
          path: '/rooms'
          method: GET
          
  postRooms:
    handler: functions/postRooms/index.handler
    events: 
      - httpApi:
          path: '/rooms'
          method: POST

  bookRoom:
    handler: functions/bookRoom/index.handler
    events:
      - httpApi:
          path: '/bookings/{roomId}'
          method: POST
  
  checkoutRoom:
    handler: functions/checkoutRoom/index.handler
    events:
      - httpApi:
          path: '/checkoutGuestWithID/{bookingID}'
          method: PATCH

  updateBookRoom:
    handler: functions/updateBookRoom/index.handler
    events:
      - httpApi:
          path: '/rooms/{userId}'
          method: PATCH
  
  getAllBookRoom:
    handler: functions/getAllBookRoom/index.handler
    events:
      - httpApi:
          path: /allBookRooms
          method: GET




resources:
  Resources:
    roomsDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rooms-db
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST